name: Vercel Deploy Preview

env:
  CI: false
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          REACT_APP_VERCEL_API_KEY=${{ secrets.VERCEL_API_KEY }} \
            REACT_APP_VERCEL_AUTH_DOMAIN=${{ secrets.VERCEL_AUTH_DOMAIN }} \
            REACT_APP_VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
            REACT_APP_VERCEL_STORAGE_BUCKET=${{ secrets.VERCEL_STORAGE_BUCKET }} \
            REACT_APP_VERCEL_MESSAGING_SENDER_ID=${{ secrets.VERCEL_MESSAGING_SENDER_ID }} \
            REACT_APP_VERCEL_APP_ID=${{ secrets.VERCEL_APP_ID }} \
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}