name: Vercel Deploy

env:
  CI: false
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Build
#        run: npm run build
#
#      - name: Deploy to Vercel
#        uses: amondnet/vercel-action@v25
#        with:
#          vercel_token: ${{ secrets.VERCEL_TOKEN }}
#          vercel-org-id: ${{ secrets.ORG_ID}}
#          vercel-project-id: ${{ secrets.PROJECT_ID}}
